### ISSUE TITLE
Feature Request: UFS mounting point resource

### ISSUE THREAD

**Issue by namoshizun** [ucloud/terraform-provider-ucloud#108]
Hiii,
I noticed while there is a nice and working `ucloud_ufs_volume` resource, there isn't a corresponding resource for the ufs mounting point. The resource would be very useful because an UFS volume itself isn't immediately usable without the mounting point attached to it...

**Comment by shawnmssu** [comment]
Thanks for your feedback, this feature is currently under development and will be available soon.

**Comment by shawnmssu** [comment]
We have released a new version [v1.30.0](https://github.com/ucloud/terraform-provider-ucloud/releases/tag/v1.30.0) about `ucloud_ufs_volume_mount_point` for this feature. Please try again.

**Comment by wangrzneu** [comment]
it seems the issue has been resolved.
