### ISSUE TITLE
Parameter duration does not take effect

### ISSUE THREAD

**Issue by jami1024** [ucloud/terraform-provider-ucloud#42]
* duration - (Optional) The duration that you will buy the instance (Default: 1). The value is 0 when pay by month and the instance will be vaild till the last day of that month. It is not required when dynamic (pay by hour).

Create a server according to the instructions, set "duration"=0, prompt Error: expected duration to be in the range (1 - 9), got 0

**Comment by shawnmssu** [comment]
This issue have been fixed in [v1.12.1](https://github.com/terraform-providers/terraform-provider-ucloud/blob/master/CHANGELOG.md), please download it and try again. Thanks for your contribution.
