### ISSUE TITLE
520 Lack of balance

### ISSUE THREAD

**Issue by yanshoutong** [ucloud/terraform-provider-ucloud#62]
I met the following issue after applying the sample code of web-server
```sh
ucloud_eip.default: Creating...
ucloud_disk.default: Creating...
ucloud_instance.web: Creating...
ucloud_eip.default: Creation complete after 3s [id=eip-addp3wvh]
ucloud_disk.default: Creation complete after 3s [id=bs-mwuwkcqt]

Error: error on creating instance, api:
[server.RetCodeError] 520 Lack of balance

  on main.tf line 23, in resource "ucloud_instance" "web":
  23: resource "ucloud_instance" "web" {

```

my terraform version is 
```sh
$ terraform -version
Terraform v0.12.21
+ provider.ucloud v1.16.0

Your version of Terraform is out of date! The latest version
is 0.12.23. You can update by downloading from https://www.terraform.io/downloads.html
```
I don't know what's wrong here, wait for your help. thanks.

**Comment by shawnmssu** [comment]
`520 Lack of balance` means insufficient account balance，please recharge the account and try again.

**Comment by yanshoutong** [comment]
OK, I got it. many thanks.
BTW: where can I find out the full list of error descriptions?

**Comment by shawnmssu** [comment]
I'm sorry about that the full list of error descriptions has not been public at present. If you like, you can join our WeChat group to facilitate timely communication.
![image](https://user-images.githubusercontent.com/41117619/76185919-9c9e3e00-620b-11ea-985a-5ada6f49ebb5.png)

**Comment by yanshoutong** [comment]
awesome, I really appriciate it. :)
Let me close this issue and see you in that WeChat group.
