### ISSUE TITLE
go v1.11 or v1.12

### ISSUE THREAD

**Issue by thatnerdjosh** [ucloud/terraform-provider-ucloud#71]
Hello!
  I stumbled upon this repository, and was going through the readme, and saw that for building 1.12 is required, but for development it says it could be built using 1.11+, is this just a piece of documentation that hasn't been updated?

Thanks

**Comment by shawnmssu** [comment]
I am sorry about that, the go version for development should be using 1.14+, and I will fix the readme about this. Thanks for your feedback.

**Comment by shawnmssu** [comment]
The problem has been resolved, we will close this issue.
