### ISSUE TITLE
peer_project_id doesn't work with ucloud_vpc_peering_connection.

### ISSUE THREAD

**Issue by hanyouqing** [ucloud/terraform-provider-ucloud#84]
There is a argument `peer_project_id` on the [documentation ](https://registry.terraform.io/providers/ucloud/ucloud/latest/docs/resources/vpc_peering_connection)， but it doesn't works to me, got error below:

```
Error: error on creating vpc peering connection, api:
[server.RetCodeError] 58002 Get resource info errors
```

`ucloud_vpc_peering_connection` works well when I just remove it.

**Comment by shawnmssu** [comment]
I checked the log just now and found that the `peer_project_id ` you passed might be wrong which is a number but we want a string like `org-xxx`.

**Comment by shawnmssu** [comment]
In addition, I learned that under the master account, support the inter-project VPC connection in the same region, VPC connection in different regions and inter-project requires the establishment of two UDPN high-speed channels.

**Comment by hanyouqing** [comment]
Yeah, you're right I got the wrong `peer_project_id`  for this,  I'm going to close this issue. Thanks!

I do have 2 VPCs in different regions but it seems that I don't have to create 2 UDPNs, only 1 UDPN instance works to me in my case.

**Comment by shawnmssu** [comment]
VPC connection in different regions and different projects requires the establishment of two UDPN high-speed channels in two projects.
In your scenario, this [example](https://github.com/ucloud/terraform-provider-ucloud/tree/master/examples/vpc) should be able to solve.
